sudo: required
dist: trusty
language: C
script: make

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y devscripts equivs
  - sudo mk-build-deps -t "apt-get --no-install-recommends -y" -r -i debian/control
env:
  global:
  - secure: x5dGu0zubDaCHbPOGZjRAS3+cvWi7DsL7CjwXjD7p/mT0U8OnKDdrE2mPhjl6rV4CCA8xSjicv/8SWWO8qoTJa/53bYaMSi4ynL5d0/eSdLfFHSzwPsaWCrlZMIngGLcjMR1JR5bSyy/85pnaG7Cre6FiBekjrsXDTCC5cTviDlz/kVZyOJcToVykodVPJU+Aiwov5MoyHJfeRQaINW/Qo9TKNBMO/8KfEf+y1YnqNicGg0uCQcqhvRswwKV1QxcckbGdnUHnl5yD2Qp6ohjDG+BUyVZZ8M7Q7kCLif3oZao6X7GUNbd2UOb6wCpysp77taYHkHhvsRjUo2PzKzeJPlhz+t/BhlrEIb36M/CsDZYir6xWj7f8gb+5l8LrK+KIZ5K1D3CmvMsjo7xtUTKFsLC+E+yeMoefbO84I6MEKvopUy7VVm6bClaOZz8CUW4izPe20HZfpTl7fmwf7sA87IMiyBeh4nlP5QhbVxX4imRzh0LmB2qLtHC0q7qsxtLw+JAbzR6TWW7jhLRiNTI/xQ+RBRyJ1WgG7mIpeI9t5f8KrmakiMBLR2+JhF4sfKmhasHbW0c/ISTsuG7BlfY5T8DaNbs1VyC5If2jto3MIOPF03KnmwzFGr2/DZKhLflXY6sWuA7DFeYmRo191NgPcjLDCb8+SB5V5MVDegq10Y=
  - secure: PO53nCfTVUeBgrgA3q62Mecba2JgzVf6M6J1cLHPmw751gh3DYWDztxNoiZhVYn9//QGVG6MEqJfZo/2fbVnbeInJWsovFMF0e6eKPFlhVm/Osz386TAHpO0RVoQDI+ad/ghHnGWiGSn15byDlolu3fTQLbgf0TCxZAp0706+gM4s9WFRa97b5Wi6vz3KBPoglAjM4Dhfv1mOzhftnile0tM53N+UOZVld7ZVZKdmm3/QCAbLgRLTHI7xBogZekPe38XNNtXkFwBscvO1gGrZ4mz7i7YTcWdjn8cpOjaK9NdxC6Yqu8KSp4z+RC9bXfftv7TklEM8ZXesdX0M5osabCuFu9xeIuHGA211lyfu004srQrIJD0LobaLDxC9URSuwg69rFRoKWj41/qf3WKxFodB4ua77lhLA1Rqc0Ay/G0ru6AeTmACFU653dzmXRd3dJcR46t8hoOd9GDFwUo+oisSqn7wlnEauwqEhsRKxu9lgkj1RDnM+rOW7UnHf00u6E4gj6vouevxnaQwkAdcUuM5xdRGGpKOIeS2YOL0MvHOoKpaFBKcH1sXDM3AzVdqMLMxMFbhgn3kGI/UyUkuB57Oj4LjhUUds1N/W6UczyA556V8fCGGfLK+dSjcqf8TcT2/06MHil+Ch2tFoYy5i75/UMz/JqDI8LcIQ51Tz8=
