version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t heroku/sffmpeg .
      - run: docker run -e "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" -e "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" heroku/sffmpeg /bin/bash -c "make deb && aws s3 cp ../sffmpeg*.deb s3://heroku-activestorage-default/sffmpeg/"
