version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t heroku/sffmpeg .
      - run:
          name: "Build deb and upload to S3 (if on master)"
          command: >
             if [ -z $CI_PULL_REQUEST ] && [ "$CIRCLE_BRANCH" = "master" ]; then
               docker run -e "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" -e "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" heroku/sffmpeg /bin/bash -c "make && make deb && aws s3 cp ../sffmpeg*.deb s3://heroku-activestorage-default/sffmpeg/"
             else
               docker run heroku/sffmpeg /bin/bash -c "make && make deb"
             fi

workflows:
  version: 2
  workflow:
    jobs:
      - build
